### ISSUE TITLE
Problems with PageExtensions and TableExtensions

### ISSUE THREAD

**Issue by StHillmann** [CloudReadySoftware/crs-al-language-extension#10]
After last update, reorganizing and renaming of tableextensions and pageextensions only works, if the object name that is being extended contains quotes and a blank character.

For example:
Renaming or Reorganizing of this object will fail:
`tableextension 50100 CustomerExt extends Customer`

Renaming or Reorganizing of this object is ok:
`tableextension 50100 CustomerExt extends "Customer "`

**Comment by waldo1001** [comment]
Thanks for testing it.  It should be solved now - please update your extension to version 0.1.12.
