### ISSUE TITLE
Use git mv when renaming and moving files

### ISSUE THREAD

**Issue by ChrisBlankDe** [CloudReadySoftware/crs-al-language-extension#100]
Use git mv when renaming and moving files so git will identify this change as rename instead of delete/create of file.

**Comment by waldo1001** [comment]
Not sure how I can do that, but wil try to find out!  Thanks for the tip!

**Comment by waldo1001** [comment]
Figured it out!  Working in on it :-)

**Comment by waldo1001** [comment]
@ChrisBlankDe , I would love for you to test this unreleased version: https://www.dropbox.com/s/96no1q5r3myhlqj/crs-al-language-extension-1.0.16.vsix?dl=0

**Comment by waldo1001** [comment]
@ChrisBlankDe , new version online (same URL), now with a setting (and some fixes) :
![image](https://user-images.githubusercontent.com/12088142/54712731-4459c200-4b0a-11e9-8a55-b5884351e178.png)

**Comment by waldo1001** [comment]
I'm temporarily put this on hold, as I'm getting headaches of this feature ;-).  Been struggling for hours, and i'm doing it (probably) completely wrong.

Problem is: new files which are not part of the repo yet.  I can basically just rename them, while files that ARE part of the repo, needs to be:
- renamed with git mv
- which moves them to "staged"
which means - if any in staged, or if I would put my changes in the renamed file to stages without committing .. I still lose it.

But biggest problem is the new files - i can't rename them with git mv.  And I don't know (yet) to find out if I would be able to rename them with "git mv" or not.. .  Seems that I have to find out how to get structured info from Git. (I'm using terminal now..)
