### ISSUE TITLE
Export some of the extension functions as API

### ISSUE THREAD

**Issue by anzwdev** [CloudReadySoftware/crs-al-language-extension#102]
Could you create a public api to allow other vs code extensions to use your functions to run objects and to create object file names using your file name patterns? It can be done by creating an "api" object and returning it from the extension activation function. A bit more information about it can be found here:
https://code.visualstudio.com/api/references/vscode-api#extensions

**Comment by waldo1001** [comment]
Are you sure I need to do that?
I just saw that this extension is already creating an "extensiondependency" without me every creating an api: https://marketplace.visualstudio.com/items?itemName=martonsagi.al-object-designer

It's just because I have no idea on how to do it (yet) :-).

**Comment by waldo1001** [comment]
Would this kind of work, you think?

![image](https://user-images.githubusercontent.com/12088142/52287262-1cebd300-296a-11e9-95b7-9a7bc74def15.png)

**Comment by waldo1001** [comment]
Thanks, @anzwdev .
May be we should make one usecase for one function so I can publish it and you can build upon that?

**Comment by anzwdev** [comment]
Making one usecase for one function seems to be a good idea. 

It would be nice to be able to call your extension and pass object type, name and id and get back file name for that object/object extension using your file renaming functionality. I was thinking about creating a pull-request, but as I can see, your NAVObject class constructor expects full object source code to extract object details from it, so a bit of refactoring might be required to be able to use it without using al object source code. This change seems to be the biggest part of my "enhancement" suggestion. Once it is done, the rest should be easy.

**Comment by waldo1001** [comment]
Thanks for implementing this!
