### ISSUE TITLE
Rename/Reorganize AL File in extension of file is in caps

### ISSUE THREAD

**Issue by AmolSalvi** [CloudReadySoftware/crs-al-language-extension#105]
I am using you tool to reorganize/rename the AL files and just found something surprising

If I used my file extension of file in capital (e.q. mytestfile.AL) then it is not reorganize or rename the file but if I used (e.q. mytestfile.al) it reorganize correctly.

Surely it is not bug but just thought I will inform you.

Ammolh Saallvi

**Comment by waldo1001** [comment]
Thanks, I'll have a look at it!
