### ISSUE TITLE
Debug Console Messages

### ISSUE THREAD

**Issue by rvanbekkum** [CloudReadySoftware/crs-al-language-extension#106]
Hi @waldo1001,

I noticed that the extension pollutes the debug console a bit, see the screenshot below:

![image](https://user-images.githubusercontent.com/7383241/54479285-8ee1f280-481b-11e9-9e52-9b4ab199ebaf.png)

I can understand logging the activation/deactivation of the extension, but I think the other messages should not be there (e.g., printing the path of my user folder from `SnippetFunctions.js`).
While developing another VSCode extension, these messages pop up every time.

Could this be cleaned up? 😉

**Comment by waldo1001** [comment]
Thanks for your message.  It makes sense to diminish the amount of logs, although I'll keep quite a few of them - since they give me a lot of feedback when something goes wrong...
