### ISSUE TITLE
Can Renaming of Table/Table Extensions update the Record Variables also automatically?

### ISSUE THREAD

**Issue by Rachit14** [CloudReadySoftware/crs-al-language-extension#112]
Hi,

I am using CRS AL Language Extension to rename AL files according to the Microsoft alloted series and prepend prefix in all AL files. After renaming of AL Tables/Table Extensions I am facing issuing in Codeunits because Record variables are still pointing to old table names. Is there any way to change all those variables automatically?

**Comment by waldo1001** [comment]
This is expected behaviour.  

I haven't found a way to "rename symbol" unfortunately. Therefor: just do this once, and make sure you rename automatically after save.  

![image](https://user-images.githubusercontent.com/12088142/55564685-b8928900-56f8-11e9-9efe-c89d8b47f802.png)

**Comment by waldo1001** [comment]
Already an open issue here:
https://github.com/CloudReadySoftware/crs-al-language-extension/issues/19
