### ISSUE TITLE
Rename command adds quotes around all object + control names

### ISSUE THREAD

**Issue by rvanbekkum** [CloudReadySoftware/crs-al-language-extension#114]
Hello @waldo1001,

When running the rename commands (i.e., "CRS: Rename - ..."), I noticed that _all_ object and control names get surrounded with quotes, also when this is not necessary (that is, if the names contain only characters from [A-Za-z0-9_]). This also concerns the source expressions of field controls.

Here I also have an example.
Before running the rename command:
![before](https://user-images.githubusercontent.com/7383241/58368150-3ac54f80-7ee9-11e9-9f55-76326ec780ab.png)

After running the rename command:
![after](https://user-images.githubusercontent.com/7383241/58368134-0baede00-7ee9-11e9-808b-88953b1e5e6d.png)

I also noticed that because of this, the rename command can also introduce errors in the file when you for example have a source expression of the form `SomeRecordVariable.SomeFieldOrProcedureCall` it will also be surrounded with quotes, resulting in a compiler error.

Could you make a change for this, maybe through a new setting?

**Comment by waldo1001** [comment]
This is actually more difficult (for me ;-)) as it seems ... .  Personally, I don't mind having the quotes there - and introducing this kind of change, could potentially cause a lot of inconsistencies ...

I'll look into it!  Thanks for the feedback!

**Comment by waldo1001** [comment]
that was a bug - thanks so much for mentioning - I never noticed :-).  New update coming up!

**Comment by rvanbekkum** [comment]
Thanks for fixing, but I noticed it only does this for the control names and source expressions. Would it also be possible to drop the quotes if the object name restricts itself to the following pattern `[A-Za-z_][A-Za-z0-9_]+`?

**Comment by Ji-Peter** [comment]
Is this still being fixed?
