### ISSUE TITLE
tfield does not show DateTime as you time

### ISSUE THREAD

**Issue by GreatScott000** [CloudReadySoftware/crs-al-language-extension#116]
Just noticed that the tfield snippet does not show DateTime as an option when you are typing in the data type.  As you type Date, you see Date and DateFormula but no DateTime

[tfield.zip](https://github.com/CloudReadySoftware/crs-al-language-extension/files/3224194/tfield.zip)

e.g.
```
tfield(25; "Some Field Name"; DateTime) {
...
}
```
See the videos in attached zip file for reference.

**Comment by GreatScott000** [comment]
Data Type of Enum doesn't show up either in Intellisense

**Comment by waldo1001** [comment]
Looking good? :-)

**Comment by GreatScott000** [comment]
Looks good thanks.

**Comment by waldo1001** [comment]
thanks for reporting - should be fixed now!
