### ISSUE TITLE
Manage TODO tags in al

### ISSUE THREAD

**Issue by waldo1001** [CloudReadySoftware/crs-al-language-extension#2]
Manage TODO tags in al

**Comment by fvet** [comment]
Are there any /what are the plans for this? Currently, I'm using '[TODO Highlight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight)'

**Comment by waldo1001** [comment]
Well, the idea is quite similar.  So I'm not sure I would be doing this one...

**Comment by waldo1001** [comment]
Couldn't find any "TODO"-extension that really works for me.  Will try to do it myself.  This is the functionality I'll try to make:
- tag todos with `//TODO: explanation`
- new command: list all todos, which lists them in a separate window (not in the output window)
- click on todo will navigate to the file/todo

**Comment by kine** [comment]
Why the TODO Highlight extension is not enough for you?

**Comment by LauraNicolas** [comment]
Check this extension: [Todo Tree](https://github.com/Gruntfuggly/todo-tree)

I think it has what you need: a tree-list of all the TODO found in all the files. (or other tags that you can define)

I have personally added a DEBUG tag, that I use when I add/remove code for debug purposes. 

Salut!
Laura Nicolàs

**Comment by vody** [comment]
> Well, not really. I'd like to have a list somewhere - with navigation to the exact places of the todo...
> or what am I missing?

[TODO Highlight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight) allows to have such a list: 
![image](https://user-images.githubusercontent.com/1209989/51090881-cb777a80-17e7-11e9-9c4e-a00f3da5e9b4.png)
Which would generate an output: 
![image](https://user-images.githubusercontent.com/1209989/51090975-d41c8080-17e8-11e9-88f5-eadaa4529cc9.png)
To make it work in .al files, just need to be sure you include .al file support though _settings.json_: 
`  
"todohighlight.include": ["**/*.al"],
"todohighlight.isEnable": true
`

**Comment by waldo1001** [comment]
TODO highlight it is :-)
