### ISSUE TITLE
If the crs extension is enabled, Ctrl+s executes also Ctrl+n

### ISSUE THREAD

**Issue by DBiernat** [CloudReadySoftware/crs-al-language-extension#21]
I dont know why, but as of today I get this strange behaviour in VS Code. If I disable the Extension everything works as expected.

Any suggestions?

**Comment by waldo1001** [comment]
Yep - that's the "donothing" that malfunctions!  Fix coming up soon!

**Comment by waldo1001** [comment]
Thanks for reporting it.  

New version is online!  Can you confirm it works?

**Comment by waldo1001** [comment]
I will close it in the meantime - but if you still have problems, please don't hesitate to report them! :-)

**Comment by DBiernat** [comment]
Hi Waldo,

I can confirm, it works! Thanks for the quick help.

Mit freundlichen Grüßen / Best regards

Dirk Biernat

Entwicklung / Development


GLI Business Solutions GmbH
Fraunhoferstraße 3
25524 Itzehoe

Telefon:      +49/0-4821-778-110
Telefax:      +49/0-4821-778-119
E-Mail:        Dirk.Biernat@gli-bs.de<mailto:Dirk.Biernat@gli-bs.de>
Internet:     http://www.main-tool.de<http://www.main-tool.de/>
                  http://www.gli-bs.de<http://www.gli-bs.de/>

[cid:image001.png@01D3DCEB.09361180]

This e-mail and any attachment thereto contain confidential and/or privileged information. If you are not the intended recipient or have received this e-mail in error, please notify the sender immediately and delete this e-mail and any attachment thereto from your system. Any unauthorized retention, copying, transmission, distribution, disclosure or use of the content of this e-mail and/or any attachment thereto is prohibited.
GLI is not liable for any omission or error in this e-mail and/or any attachment thereto which may arise as a result of the e-mail-transmission or for damages resulting from any unauthorized change of the content of this e-mail and/or any attachment thereto.
Thank You

GLI Business Solutions GmbH • Geschäftsführer: Eggert Pfeiffer, Marc Pfeiffer • Amtsgericht Pinneberg HRB 1560 IZ

**Comment by waldo1001** [comment]
thanks for using it ;-)
