### ISSUE TITLE
Re-organize - Current File Doesn't Save Changes

### ISSUE THREAD

**Issue by DavidRoys** [CloudReadySoftware/crs-al-language-extension#27]
I made a silly mistake and ran the Re-organize Current File command before saving my changes. My changes were lost. :-( I won't make that mistake again, but is there any way you can save the file before renaming it?

**Comment by waldo1001** [comment]
Thanks @DavidRoys  - it makes all the sense to save before reorg.  I did this in the past, but VSCode changed its api a bit, so I have to find another way to save the file(s).  Shouldn't be hard to do.

I'll keep this issue!

**Comment by waldo1001** [comment]
Should be fixed in latest release
