### ISSUE TITLE
Can the Extended Object ID be moved to the end of the file name instead of just after the Tab?

### ISSUE THREAD

**Issue by DavidRoys** [CloudReadySoftware/crs-al-language-extension#29]
For example, currently I get:

Tab81-Ext50001.PREFGenJnlLine.al

But I would like to get:

Tab-Ext50001.PREFGenJnlLine.81.al

The reason being is that by including it just after Tab, my files are no longer sorted by the ID I have used which means I cannot easily see which is the next available object ID for that object type. Sorry, I haven't looked up what Microsoft recommend for this in their file naming standard.

**Comment by waldo1001** [comment]
Hi @DavidRoys ,

this is already possible.  there is a setting "CRS.FileNamePatternExtensions" that can do that for you.  Just set it up like this:
`"CRS.FileNamePatternExtensions": "<ObjectTypeShort>-Ext<ObjectId>.<ObjectNameShort>.<BaseId>.al"`

**Comment by waldo1001** [comment]
But as I understood, the default setting is indeed the MIcrosoft recommended way..
