### ISSUE TITLE
Run Object (Windows Client) - Change server settings

### ISSUE THREAD

**Issue by maze93** [CloudReadySoftware/crs-al-language-extension#44]
Hi!

Does anybody know how to change the server settings when using Run Object (Windows Client)?
Our development environment exists on one server and the NAV server exists on another. The CRS is always looking for 'NAV' on server 'localhost' and that isn't sufficient enough for me.

Any thoughts?

Thanks!

Regards from Mattias

**Comment by fvet** [comment]
@waldo1001, maybe related to the above, but I'm facing an issue when using the 'CRS : Run Object' commands. They seem to use the launch.json 'server' setting (which fails in my case), whereas I guess MS is using the 'publicwebbaseurl' from the server settings instead (which runs the objects / clients without any issues).

The above 2 settings are different on my setup (IP vs servername)

**Comment by waldo1001** [comment]
@maze93, @fvet,

did you try to change te following settings:
![image](https://user-images.githubusercontent.com/12088142/41239510-c149d4b2-6d98-11e8-8238-0b4abb3913eb.png)

Default is indeed "localhost", but you can change it.. .

For web client, it's reading the launch.json, indeed - like the deploy is doing as well.

**Comment by waldo1001** [comment]
@fvet,

If the deploy works, the run client should work as well - can't you change the setting in launch.json to the public web-url instead?  I'm not able to repro the scenario :-/

**Comment by waldo1001** [comment]
Just FYI,

there is a list of setting on this page:
https://marketplace.visualstudio.com/items?itemName=waldo.crs-al-language-extension

There are all Win-server-settings
```
CRS.WinServer: Server where the windows client is connecting to
CRS.WinServerInstance: Serverinstance where the windows client is connecting to
CRS.WinServerInstancePort:Portnumber of the serverinstance where the windows client is connecting to
```

**Comment by waldo1001** [comment]
@maze93, @fvet,

I'm not able to repro any of the problems you mention.

Therefor a suggestion: would it be an idea to have a setting like "crs.PublicWebBaseUrl" that would override the default launch-settings?

**Comment by fvet** [comment]
Due to some internal restrictions, I'm (currently) obliged to use the IP as 'server' in the launch.json (to publish extension / download symbols). When published, the WebClient can't be run using the IP, so therefore the publicwebbaseurl was set differently on the NST.

Having 'crs.publicwebbaseurl' would be a good option!

**Comment by waldo1001** [comment]
@fvet, @maze93 ,

New setting is live!  I tested it - should work ;-)

**Comment by fvet** [comment]
It does work ;) 
Thanks!

**Comment by lvanvugt** [comment]
Hi Eric,

Trying to get this working. But were to do this?

> did you try to change te following settings:
![image](https://user-images.githubusercontent.com/18466198/44864521-27e65d00-ac80-11e8-9f90-cc3703753fd5.png)
> Default is indeed "localhost", but you can change it.. .
> For web client, it's reading the launch.json, indeed - like the deploy is doing as well.
