### ISSUE TITLE
ObjectNamePrefix conflicts with Autoformat - spaces are removed

### ISSUE THREAD

**Issue by fvet** [CloudReadySoftware/crs-al-language-extension#47]
I'm using

```
 "[al]": {
        "editor.formatOnSave": true
    },
```

which formats fields as below when saving my changes (mind the space before the field name)

`field(1; "Code"; Code[10])`

However, when renaming all files via the CRS extension, in combination with "CRS.ObjectNamePrefix" set, my files are changed to 

`field(1;"Code"; Code[10])`

**Comment by waldo1001** [comment]
Yep - true.  Will be fixed in next release!

**Comment by waldo1001** [comment]
@fvet - should be fixed!
