### ISSUE TITLE
<BaseName> tag removes spaces from object name

### ISSUE THREAD

**Issue by MikeGlue** [CloudReadySoftware/crs-al-language-extension#48]
When using the 'BaseName' property in the 'CRS.FileNamePatternExtensions' property, the result is that spaces are removed from the base object's name (example: BinContent). This seems to be inconsistent with using the 'ObjectName' property whish does not remove any spaces. I don't think that spaces should be removed in 'BaseName'.

**Comment by waldo1001** [comment]
You are right (again). :-)

Will fix!  
Will introduce a BaseNameShort, and leave alone the BaseName

**Comment by waldo1001** [comment]
@MikeGlue  - Should be fixed now!
