### ISSUE TITLE
Rename - all files issue

### ISSUE THREAD

**Issue by pmohanakrishna** [CloudReadySoftware/crs-al-language-extension#54]
If we have object name with () at end then rename -all files creating as below
![image](https://user-images.githubusercontent.com/23735402/41710906-708332b6-7564-11e8-910f-efe3433f3954.png)

**Comment by waldo1001** [comment]
I'm in the process of acception a pullrequest that might fix this as well - so let me create a test that reproduces this error - and go from there!

thanks for taking the time to log!

**Comment by waldo1001** [comment]
Should be fixed in this new release!
