### ISSUE TITLE
Add an option to remove prefix/suffix from filenames

### ISSUE THREAD

**Issue by jwikman** [CloudReadySoftware/crs-al-language-extension#55]
Since a prefix or suffix is mandatory for an AppSource app, it's pretty convenient to let this extension take care of the naming.

But having the same prefix in every filename makes the Explorer tree in VSCode unnecessary hard to skim through. At least my eyes tends to focus on the pattern (and that's the prefix). 

So I suggest to add an new setting: "Remove prefix from filename".

I can create a PR for that if you think it's a good idea, but don't have the time. ;)

**Comment by waldo1001** [comment]
Thanks so much, @jwikman .  You're such a great help!
I'm buying you beers some day!  (the real deal - Belgian beers that is ;-))

**Comment by jwikman** [comment]
I will hold you to that promise 😉
