### ISSUE TITLE
Reorganize files : All Files does not always work.

### ISSUE THREAD

**Issue by fvet** [CloudReadySoftware/crs-al-language-extension#6]
When using the 'Reorganize - All Files', some AL files (not all) are often skipped, although when using 'Reorganize - Current File', the file gets properly renamed. I mainly get this issue after I had to renumber (or rename) the AL objects.

**Comment by waldo1001** [comment]
Thanks for mentioning.
It reads the first line of the file, and then applies a regex.

Can you give me an example, so I can debug?

fyi,
I'm going to match the new guidelines:
https://docs.microsoft.com/en-us/dynamics-nav/compliance/apptest-bestpracticesforalcode
would that work for you?

**Comment by waldo1001** [comment]
Let's see if I can replicate ...

**Comment by waldo1001** [comment]
can I see what's the first line of report 71000?

**Comment by fvet** [comment]
Just some default properties

```
report 71000 "CGK CMR"
{
    DefaultLayout = RDLC;
    RDLCLayout = './Reports/CGK CMR.rdlc';
    CaptionML = ENU = 'Waybill',
    FRB = 'Lettre de voiture',
    NLB = 'Vrachtbrief';

    dataset
    {
```

**Comment by waldo1001** [comment]
It looks like the report in your screenshot is the same name and a different number?

**Comment by fvet** [comment]
I've updated the code sample above with the correct id. I'm indeed experimenting with the renumbering of objects, so names are unchanged, object numbers are in my scenario.

**Comment by waldo1001** [comment]
You were right, only letters were accepted.
What I'll do is to accept four characters:
```
.
/
_
-
```
and all numbers.

Makes sense?

**Comment by waldo1001** [comment]
I uploaded a new version - please test :-)

**Comment by waldo1001** [comment]
Will do!
Forgot about that :-/.

**Comment by waldo1001** [comment]
Done! 
Please test again :-)
