### ISSUE TITLE
Only apply prefix/suffix (on actions/fields) on extension objects

### ISSUE THREAD

**Issue by waldo1001** [CloudReadySoftware/crs-al-language-extension#60]
No need to provide action/field prefixes on new objects.

**Comment by waldo1001** [comment]
@dkatson, I have one problem with this.
What if people already are using the extension like this - it would all of a sudden rename all their fields.

So I kind of have to leave the default option as "rename all", and make a setting like "OnlyPrefixExtensionObjects", which is default to "false", don't you think?

**Comment by dkatson** [comment]
Would be a solution.
However i think you can change “OnlyPrefixExtensionObjects” to “PrefixActionsOnObjects” with options : “All”, “Only extensions”. With All as default. That could give you better flexibility for future updates of AL. Who knows what Ms will invent :)

Dmitry

**Comment by waldo1001** [comment]
Hm, ok, and add another one “PrefixFieldsOnObjects” with same options, correct?

**Comment by dkatson** [comment]
I did not noticed that current version adds prefix to a fields on
extensions objects. So do we need that configuration
"PrefixFieldsOnObjects" ?

**Comment by waldo1001** [comment]
@dkatson ,

I decided to NOT use any new setting.  It will not remove any prefix anyway - it's just not setting anything going forward ;-) - at least not on the places we were talking about.
