### ISSUE TITLE
Small bug: Src folder should be lowercase

### ISSUE THREAD

**Issue by spookymattress** [CloudReadySoftware/crs-al-language-extension#62]
When reorganizing files the folder 'Src' is created and the files are reorganized.

But according to the best practices, the folder names should be lowercase.

> An extension is fully contained in a single folder. This folder often contains multiple files, such as app.json and launch.json files, perhaps an image file representing the extension's logo, various folders for source; "\src", other resources; "\res", and a test folder; "\test" folder. The extension does not need to follow a flat structure, which means that, depending on the amount of application files, additional folders can be used in the "src" or "test" folders to group objects based on their functionality, which can help make maintaining a large .al project easier.

**Comment by spookymattress** [comment]
created a pull request.

**Comment by waldo1001** [comment]
Thanks! Will be part of the next release!

However - I got this exact naming from on of Microsoft's extensions ;-) - so I don't consider this a bug :p
