### ISSUE TITLE
Auto naming for Extension Objects

### ISSUE THREAD

**Issue by waldo1001** [CloudReadySoftware/crs-al-language-extension#64]
I could do some kind of “auto renaming”, based on a “CRS.ExtensionObjectPattern”-setting, which includes the name of the object it extends and some ... (like “<BaseName> Ext”).  And only do that when you rename the file (or OnSaveAction) – with no ability for you to change the name.

**Comment by OldNavDog** [comment]
Waldo, thanks for the lightning (and thoughtful!) response! I thought you said you were busy, LOL!!!

I tried mightily for about 6 hours the other day, trying to do this with Regular Expressions in VSC; but all I got out of it was a renewed hatred for Regex...

The template my particular “Project Mgr” (the “Project” being ‘Converting our C/AL Add-Ons into 2.0 Extensions’) was desiring was the following:

[Prefix][BaseName] [ObjectTypeShort]Ext

Eg. **CCSItem List PagExt**

It would be wonderful if it could also work with (or also in the fashion of) your “Rename All” Command.

And as far as I am concerned, It would be fine that you couldn't change the name. I just wouldn't enable the "OnSave" option.

Would this become a new CRS Command, with its own "Settings" for the Template? That would likely be best, in my opinion.

**Comment by waldo1001** [comment]
I think this would make sense:

A new setting: "CRS.ExtensionObjectNamePattern".
Default: ""
When "" -> manual naming
When filled in -> automatic naming
Available tags: -> <Prefix><Suffix><ObjectType><ObjectTypeShort><ObjectTypeShortUpper><ObjectId><BaseName><BaseNameShort><BaseId>

Would work?

**Comment by OldNavDog** [comment]
Looks reasonable to me!

**Comment by waldo1001** [comment]
lol, my tages weren't visible :-)

**Comment by OldNavDog** [comment]
Now it looks even MORE reasonable, LOL!

So why don't I have it yet?  ;-)

**Comment by OldNavDog** [comment]
BTW, how'd you get the comment-editor to let you show "angle brackets"? It ATE mine!

**Comment by waldo1001** [comment]
insert it in code...

**Comment by OldNavDog** [comment]
Duh, I wondered about that. Thanks!

**Comment by waldo1001** [comment]
Done!
Hope you like it ;-)

**Comment by OldNavDog** [comment]
Waldo,

That is SWEET!!!!!!

You have officially earned your Weekend!!!

Thanks a million!!!

BTW, is there REALLY any difference between a Prefix and a Suffix (IOW, can I just put my “Prefix” at the End of something and call it good?)

Thanks again,

-Doug


this is a placeholder
Doug McIntosh
[DougSkype]
this is also a placeholder
Doug McIntosh
Cost Control Software<http://www.costcontrolsoftware.com/>
Phone: 317-846-6025 (office); 317-373-5050 (cell)
Email: doug@costcontrolsoftware.com<mailto:joseph@costcontrolsoftware.com>

Click here for current Price Catalog<https://costcontrolsoftware.leadpages.co/leadbox/141df29f3f72a2%3A113e88a1eb46dc/5697982787747840/>
Click here for current DVD Training Catalog<https://costcontrolsoftware.leadpages.co/leadbox/142882473f72a2%3A113e88a1eb46dc/5698497110081536/>
