### ISSUE TITLE
ttrigger within field

### ISSUE THREAD

**Issue by GreatScott000** [CloudReadySoftware/crs-al-language-extension#66]
When I use the ttrigger (CRS) snippet I seem to always get an extra set of parenthesis at the end of the trigger.  Is there something I am missing?  Why are they there.

![image](https://user-images.githubusercontent.com/4333956/42682331-2ee7c338-8682-11e8-8ab7-8ea2c8ea0ff3.png)
![image](https://user-images.githubusercontent.com/4333956/42682336-34d4548c-8682-11e8-88f0-26eea9f87aa5.png)

**Comment by waldo1001** [comment]
No, it's the new compiler that's adding these brackets.  
I'll fix my snippet - wasn't aware :-) (never use the ttrigger snippet ;-))
