### ISSUE TITLE
Snippet Request: Flowfield Snippets

### ISSUE THREAD

**Issue by GreatScott000** [CloudReadySoftware/crs-al-language-extension#67]
It would be nice to have a group of snippets for flowfields.  I always fumble over the Calcformula so a snippet would help with that.  It wouldn't include DataClassification as it is not available on flowfields and I would suggest `Editable = false;` as flowfields almost always are non-editable.

```
        field(15; "Item Description"; Text[50])
        {
            Caption = 'Item Description';
            Editable = false;
            FieldClass = FlowField;
            CalcFormula = lookup(Item.Description where ("No." = field("Item No.")));
        }
```

**Comment by GreatScott000** [comment]
Yes, Exactly.

**Comment by waldo1001** [comment]
Can take a while - I'll be on holiday for the next weeks :-).
