### ISSUE TITLE
Report Reorganize - takes the Object type case sensitive, so doesn't work when PascalCased

### ISSUE THREAD

**Issue by Hilbekale** [CloudReadySoftware/crs-al-language-extension#74]
I have an issue with a report "ProcessingOnly = true". This report is always moved to the main folder and is not sorted in the report folder.

Can you check this?

**Comment by waldo1001** [comment]
I most certainly will - can you show me the first line of the report?

**Comment by waldo1001** [comment]
I need the exact name... the entire first line ... (which is the only line I look at ;-))

**Comment by Hilbekale** [comment]
Report 5319465 "SUP Supplier Rating Batch"

**Comment by waldo1001** [comment]
Ok - for now, use lower-case "report" in stead of "Report".  
Apparently I have some "uppercasing" issue ;-).
Will be solved in next update!  Thanks for noticing!
