### ISSUE TITLE
Run Object (Web Client) seems not to work ...

### ISSUE THREAD

**Issue by lvanvugt** [CloudReadySoftware/crs-al-language-extension#75]
... but probably it's me.

If I run the form VSCode command palette and select Page as object type and 31 as object ID, the URL is:

`http://localhost/DynamicsNAV110/WebClient?tenant=default&Page=31`

It is missing the port for the web client (in my case default 8080).

How come?

And if I select Table as object type the web client errors.

**Comment by waldo1001** [comment]
Hi @lvanvugt ,

It's a user setting.  Just open User Settings from the command palette, and complete the winserver-settings.  You can apply port number and server..
![image](https://user-images.githubusercontent.com/12088142/44907678-0be2ca00-ad19-11e8-93d9-7d0882d08dc3.png)

**Comment by lvanvugt** [comment]
Hi Eric,

Thanx and clear. Maybe it's my pair of old eyes that didn't see this described somewhere.

**Comment by waldo1001** [comment]
Hi @lvanvugt , does it mean it works for you now?

**Comment by waldo1001** [comment]
May be because you didn't apply the WinServerInstance?  By default it's "NAV", but maybe it's different in your case?

![image](https://user-images.githubusercontent.com/12088142/45225143-1b838500-b2bc-11e8-8e05-dd712b284392.png)

**Comment by lvanvugt** [comment]
Indeed it's different so I add
> "CRS.WinServerInstance" : "DynamicsNAV110"

but to no avail.

**Comment by waldo1001** [comment]
Hm, then I keep it open – but I’d like to see your specific case.

You happen to be on DirectionsUS – so you can show me?

**Comment by waldo1001** [comment]
@lvanvugt , still a problem?  I just can't get this replicated :(

**Comment by lvanvugt** [comment]
Well, didn't use it as it was not working, but now checked and it works. I am cllsing the issue.
