### ISSUE TITLE
Trigger Snippet not working as I expect with Intellisense

### ISSUE THREAD

**Issue by GreatScott000** [CloudReadySoftware/crs-al-language-extension#80]
When I use the `ttrigger `snippet, be it for a table field, page field, table trigger, page trigger I get the standard 
```
    trigger OnWhat()
    begin
        
    end;
```
but when I start typing over the OnWhat if don't get Intellisense.  I have to "terminate" (press escape) the snippet and then I can get the Intellisense.  Here is a little gif of what happens, am I doing something wrong?

![2018-10-03_11h01_18](https://user-images.githubusercontent.com/4333956/46404064-14556880-c6fc-11e8-97f9-3d0fd521259a.gif)

--------------------
Version information: 
CRS AL Language Extension 1.04, 
AL Language 2.0.48254, VS Code,
VS Code Info
Version: 1.27.2 (user setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by waldo1001** [comment]
I'm afraid there is nothing I can do about that.  It's default behaviour as far as I know (the default snippet behaves the same.  there is not much you can do about behaviour of snippets :(.
