### ISSUE TITLE
Is the file naming is against convention?

### ISSUE THREAD

**Issue by waldotest** [CloudReadySoftware/crs-al-language-extension#88]
Hi, I renamed all of the object in my solution, but the extensions end up with names like

"Pag-Ext50501.MyPage.al", when the source document is
Pageextension 50501 "MyPage" extends "Posted Sales Shipments"

Whereas Microsoft's documentation recommends:
page 1234 "MyPag" extends "Customer Card"
-> Pag21-Ext1234.MyPag.al

( https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode )

**Comment by larswestman** [comment]
I noticed the same. Here's my settings and the result after renaming

![2018-10-30_23-10-02](https://user-images.githubusercontent.com/43792551/47753911-75d80b00-dc99-11e8-8ecb-92c2b342660b.jpg)

**Comment by waldo1001** [comment]
At this point, that's expected behaviour, as I'm not able to read the BaseId from the symbols.  That's why I rely on the fact you give the BaseId as a comment, like in this screenshot:
![image](https://user-images.githubusercontent.com/12088142/47971019-114bf000-e08d-11e8-994c-a25dab99a592.png)
