### ISSUE TITLE
Rename extension objects

### ISSUE THREAD

**Issue by BrianThorChristensen** [CloudReadySoftware/crs-al-language-extension#91]
Hi Waldo,

It's a big help to rename project files in a consistent manner, but I am missing the same functionality for tableextension and pageextension files.

Could you please update the rename function to include these object types?

Kind regards,
Brian Christensen

**Comment by waldo1001** [comment]
Hi  Brian,

What doesn't work?  It should rename table- and pageextensions as well.  There are even settings to set the pattern: `CRS.ExtensionObjectNamePattern`

**Comment by waldo1001** [comment]
@BrianThorChristensen ,
no problem at all - glad it works ;-)
