### ISSUE TITLE
Add Prefix/Suffix to pageextension Groups and Fields

### ISSUE THREAD

**Issue by jwikman** [CloudReadySoftware/crs-al-language-extension#93]
We just failed on AppSource technical validation because of AppSourceCop rule AS0011, "A prefix is required". We had missed to prefix Groups and Fields on PageExtensions.

It seems as if that AS0011 is not working for me at all, so this was a bit annoying since it's so easy to fix.

Anyway, it would be great if this extensions put prefixes/suffixes on Group and Field names on page extensions in the same way as actions and table fields are handled.

**Comment by jwikman** [comment]
Yeah, I don't get why that rule is not working for me... 

It should be quite straight forward with the same approach you used for fields and actions. :-)

**Comment by waldo1001** [comment]
Oh, so you tried to implement it in the extension?

**Comment by waldo1001** [comment]
let's call it "an enhancement" ;-)

**Comment by waldo1001** [comment]
@jwikman , I have a test version here: 
https://www.dropbox.com/s/96no1q5r3myhlqj/crs-al-language-extension-1.0.16.vsix?dl=1

would be great if you can check it out!

**Comment by jwikman** [comment]
Did you test it yourself? (except unit testing) ;-)
It didn't work for me...

But after [PR#108 ](https://github.com/CloudReadySoftware/crs-al-language-extension/pull/108) it seems to work as intended.

**Comment by waldo1001** [comment]
Thanks, @jwikman , and sorry to have wasted your time.  I'm ashamed .. and no, I clearly didn't manually tested.  Even worse, I had a bug in my test which made it work :(.  I suck ...

Anyway - new version of the file as been uploaded under te same link!  And thanks again!
https://www.dropbox.com/s/96no1q5r3myhlqj/crs-al-language-extension-1.0.16.vsix?dl=1

**Comment by jwikman** [comment]
Now it works as intended.

You don't suck, you just prove that you're also human. ;-)

Bugs in tests could be a bit tricky...
