### ISSUE TITLE
Bug with CRS.ObjectNamePrefix

### ISSUE THREAD

**Issue by LauraNicolas** [CloudReadySoftware/crs-al-language-extension#94]
Hi,

I've been using the CRS.ObjectNamePrefix setting so that the extension will add my prefix if I forget it. Very useful! Thanks for the great job, and for sharing it with the community.

I have found a bug when inserting comment on top of the file.
I this case:

```
/*
D81 001 00000000B81" AAA 2017.12.26 Some text
*/

table 57400 "Table Name"
{
}
```

I get this:

```
/*
D81 001 "MyPrefix 00000000B81" AAA 2017.12.26 Some text
*/

table 57400 "Customer Risk"
{
}
```

MyPrefix is added in the comment section, instead of on the table name definition.

Salut!
Laura Nicolàs

**Comment by waldo1001** [comment]
Can you give me exact texts?  Could it be that "00000000B81" is your table name?

**Comment by LauraNicolas** [comment]
The name of the table is "Customer Risk".

The comment 00000000B81 is just a task code with leading 0s. The name of the table is not part of the comment.

**Comment by LauraNicolas** [comment]
Full example:

I have this: 

```
/*
D81 001 00000000B81 AAA 2017.12.26 Some text
*/
table 50901 "Customer Risk"
{
    DataClassification = ToBeClassified;

    fields
    {
        field(1; MyField; Integer)
        {
            DataClassification = ToBeClassified;

        }
    }

    keys
    {
        key(PK; MyField)
        {
            Clustered = true;
        }
    }
}
```

After saving the file, I get this:
```
/*
D81 001 "**TorIns** 00000000B81" AAA 2017.12.26 Some text
*/
table 50901 "Customer Risk"
{
    DataClassification = ToBeClassified;

    fields
    {
        field(1; "MyField"; Integer)
        {
            DataClassification = ToBeClassified;

        }
    }

    keys
    {
        key(PK; MyField)
        {
            Clustered = true;
        }
    }
}
```

It also happens if the comment is with the // format (instead of /* */)

Salut!
Laura Nicolàs

**Comment by waldo1001** [comment]
Should be fixed with the latest version.  Thanks for taking the effort of reporting this!

**Comment by LauraNicolas** [comment]
Great! Many Thanks.
