### ISSUE TITLE
Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by lvanvugt** [CloudReadySoftware/crs-al-language-extension#99]
Trying to rename all my .al files in my project using the CRS VSCode AL extension. I do not succeed as it throws the error:
Cannot read property 'toUpperCase' of undefined

Any idea what is wrong?

**Comment by waldo1001** [comment]
@lvanvugt , is there a project I can test with?  Would like to debug..

**Comment by lvanvugt** [comment]
[ITDApp.zip](https://github.com/CloudReadySoftware/crs-al-language-extension/files/2804053/ITDApp.zip)
This one.

**Comment by waldo1001** [comment]
It was "junk" in the file "Codeunit 229 Document-Print".  Apparently, I don't handle "junk" too well ;-).
I have a fix in the next release (soon!)

**Comment by lvanvugt** [comment]
Apparently me neither in this case. 😉
